### ISSUE TITLE
Null geometry cannot be converted to a point. 

### ISSUE THREAD

**Issue by yardern** [hamiltoncj/qgis-poiexport-plugin#3]
Trying to use it in "QGIS version 3.32.3-Lima" to export a GeoPackge with points, got error (the native export works):

An error has occurred while executing Python code: 

ValueError: Null geometry cannot be converted to a point. 
Traceback (most recent call last):
  File "C:\Users/test/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\poiexport\poiExportDialog.py", line 98, in accept
    self.processSingleCat(self.selectedLayer, base, defaultCategory, poiNameCol, defaultPOI, descriptionCol, commentCol, linkCol, symCol, visualCol)
  File "C:\Users/test/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\poiexport\poiExportDialog.py", line 114, in processSingleCat
    point = self.transform4326.transform(f.geometry().asPoint())
ValueError: Null geometry cannot be converted to a point.

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.32.3-Lima Lima, 67d46100b5

**Comment by yardern** [comment]
My bad, found a point without Geometry.
